# LO Clickthrough data cleaning

This dataset cleans up Datathon LO Clickthrough.csv dataset and is meant to later be joint with LO Campaign Reponse dataset

In [829]:
import pandas as pd
import numpy as np

In [830]:
df_click = pd.read_csv("RawData/Datathon LO Clickthrough.csv")
#df_camp = pd.read_csv("RawData/Datathon LO Campaign Response.csv")

In [831]:
start_mem = df_click.memory_usage(index=True, deep=True).sum()

In [832]:
df_click.columns

Index(['LuminateID', 'ImportIDPartial', 'home_zip', 'Email', 'Campaign_Name',
       'Message_Name', 'Clickthrough__Date', 'URL', 'home_country',
       'home_phone', 'primary_email', 'secondary_email',
       'preferred_email_format'],
      dtype='object')

In [833]:
df_click.shape

(11848, 13)

In [834]:
df_click.head()

LuminateID  ImportIDPartial home_zip  Email  \
0     1283212              NaN      NaN  Given   
1     1283212              NaN      NaN  Given   
2     1287011              NaN      NaN  Given   
3     1286854              NaN      NaN  Given   
4     1267491         433929.0  L5M 6P6  Given   

                             Campaign_Name                   Message_Name  \
0  New Subscriber Welcome Series - General               Email 1 - Survey   
1  New Subscriber Welcome Series - General      Email 2 - Survey Reminder   
2  New Subscriber Welcome Series - General               Email 1 - Survey   
3  New Subscriber Welcome Series - General               Email 1 - Survey   
4                        2018 Spring Match  General 1  (General 1 - TEST)   

  Clickthrough__Date                                                URL  \
0   05/15/2018 10:56                             http://www.convio.com/   
1   05/22/2018 12:05  http://thcf.convio.net/site/PageServer?pagenam...   
2    09/29/2018 8:32  http://thcf.convio.net/site/PageServer?pagenam...   
3   09/28/2018 23:16  http://thcf.convio.net/site/PageServer?pagenam...   
4   06/19/2018 14:13  http://thcf.convio.net/site/Donation2?df_id=27...   

  home_country home_phone primary_email secondary_email  \
0          NaN        NaN         Given             NaN   
1          NaN        NaN         Given             NaN   
2          NaN        NaN         Given             NaN   
3          NaN        NaN         Given             NaN   
4       Canada      Given         Given             NaN   

   preferred_email_format  
0                     1.0  
1                     1.0  
2                     1.0  
3                     1.0  
4                     NaN

In [835]:
df_click.shape

(11848, 13)

In [836]:
df_click.isna().sum()

LuminateID                    0
ImportIDPartial               7
home_zip                    671
Email                        46
Campaign_Name                 0
Message_Name                  0
Clickthrough__Date            0
URL                           0
home_country                  6
home_phone                 4086
primary_email                46
secondary_email           11842
preferred_email_format     8268
dtype: int64

In [837]:
df_click[df_click.duplicated()].shape

(173, 13)

# Secondary Email

## DROP

In [838]:
df_click.shape[0] - df_click[df_click["secondary_email"].isna()].shape[0]

6

In [839]:
df_click["secondary_email"].unique()

array([nan, 'Given'], dtype=object)

### There is only 6 ppl that filled in secondary email, I will delete this column

In [840]:
try:
    df_click = df_click.drop("secondary_email", axis=1)
except ValueError:
    print("Looks like it has already been dropped...")


df_click.columns

Index(['LuminateID', 'ImportIDPartial', 'home_zip', 'Email', 'Campaign_Name',
       'Message_Name', 'Clickthrough__Date', 'URL', 'home_country',
       'home_phone', 'primary_email', 'preferred_email_format'],
      dtype='object')

# LuminateID

In [841]:
df_click["LuminateID"] = df_click["LuminateID"].dropna()

In [842]:
df_click["LuminateID"].isna().any()
# No missing values

False

In [843]:
print(df_click["LuminateID"].min())
df_click["LuminateID"].max()

1001541


1287157

In [844]:

df_click["LuminateID"].memory_usage()

94864

In [845]:
df_click["LuminateID"] = df_click[["LuminateID"]].astype(np.uint32)
# int16 was too small 

In [846]:
df_click["LuminateID"].memory_usage()

47472

In [847]:
print(df_click["LuminateID"].min())
df_click["LuminateID"].max()

1001541


1287157

# ImportIDPartial

### DROP

In [848]:
try:
    df_click = df_click = df_click.drop("ImportIDPartial", axis=1)
except ValueError:
    print("Looks like it has already been dropped...")
    
df_click.columns

Index(['LuminateID', 'home_zip', 'Email', 'Campaign_Name', 'Message_Name',
       'Clickthrough__Date', 'URL', 'home_country', 'home_phone',
       'primary_email', 'preferred_email_format'],
      dtype='object')

In [849]:
df_click.columns

Index(['LuminateID', 'home_zip', 'Email', 'Campaign_Name', 'Message_Name',
       'Clickthrough__Date', 'URL', 'home_country', 'home_phone',
       'primary_email', 'preferred_email_format'],
      dtype='object')

# Home Phone

In [850]:
df_click["home_phone"].unique()

array([nan, 'Given'], dtype=object)

In [851]:
df_click["home_phone"] =  df_click["home_phone"].fillna(value="Not-Given")

In [852]:
df_click["home_phone"].unique()

array(['Not-Given', 'Given'], dtype=object)

In [853]:
df_click.columns

Index(['LuminateID', 'home_zip', 'Email', 'Campaign_Name', 'Message_Name',
       'Clickthrough__Date', 'URL', 'home_country', 'home_phone',
       'primary_email', 'preferred_email_format'],
      dtype='object')

# Home ZIP

In [854]:
df_click[df_click["home_zip"].isna()]["home_country"].value_counts()

Canada    666
Name: home_country, dtype: int64

### All missing ZIP codes are Canadian

In [855]:
df_click.columns

Index(['LuminateID', 'home_zip', 'Email', 'Campaign_Name', 'Message_Name',
       'Clickthrough__Date', 'URL', 'home_country', 'home_phone',
       'primary_email', 'preferred_email_format'],
      dtype='object')

# Email

In [856]:
df_click["Email"] =  df_click["Email"].fillna(value="Not-Given")

In [857]:
df_click[df_click["Email"] == "Not-Given"][["Email"]].count()

Email    46
dtype: int64

## Primary Email and Email are same

In [858]:
df_click[df_click["primary_email"].isna()]["primary_email"].shape

(46,)

In [859]:
df_click["Email"].unique()

array(['Given', 'Not-Given'], dtype=object)

# Primary Email

## DROP since same as Email

In [860]:
try:
    df_click = df_click.drop("primary_email", axis=1)
except ValueError:
    print("Looks like it has already been dropped...")
    
df_click.columns

Index(['LuminateID', 'home_zip', 'Email', 'Campaign_Name', 'Message_Name',
       'Clickthrough__Date', 'URL', 'home_country', 'home_phone',
       'preferred_email_format'],
      dtype='object')

# Home Country

In [861]:
df_click["home_country"].unique()

array([nan, 'Canada', 'United Arab Emirates', 'United States',
       'Australia', 'USA'], dtype=object)

In [862]:
df_click = df_click.dropna(subset=["home_country"])
df_click.shape

(11842, 10)

In [863]:
df_click["home_country"].unique()

array(['Canada', 'United Arab Emirates', 'United States', 'Australia',
       'USA'], dtype=object)

In [864]:
df_click.columns

Index(['LuminateID', 'home_zip', 'Email', 'Campaign_Name', 'Message_Name',
       'Clickthrough__Date', 'URL', 'home_country', 'home_phone',
       'preferred_email_format'],
      dtype='object')

# Preferred email format

## DROP

In [866]:
df_click["preferred_email_format"].value_counts()

0.0    3412
1.0     152
2.0      11
Name: preferred_email_format, dtype: int64

In [867]:
try:
    df_click = df_click.drop("preferred_email_format", axis=1)
except ValueError:
    print("Looks like it has already been dropped...")
    
df_click.columns

Index(['LuminateID', 'home_zip', 'Email', 'Campaign_Name', 'Message_Name',
       'Clickthrough__Date', 'URL', 'home_country', 'home_phone'],
      dtype='object')

# FINAL TOUCHES

# % of missing ZIP codes

In [886]:
df_click.isna().sum()

LuminateID              0
home_zip              666
Email                   0
Campaign_Name           0
Message_Name            0
Clickthrough__Date      0
URL                     0
home_country            0
home_phone              0
dtype: int64

In [885]:
666 / 118.42 

5.624049991555481

# Grouping up based on LuminateID and CampaingDate and taking the clickthrough with the last name

### And create new column with counts of clickThroughs in each column 

In [889]:
df_click_new = df_click.sort_values(by=['LuminateID',"Campaign_Name", 'Clickthrough__Date']).drop_duplicates(subset=['LuminateID',"Campaign_Name"])

In [898]:
df_click_new = df_click.sort_values(by=['LuminateID',"Campaign_Name", 'Clickthrough__Date']).drop_duplicates(subset=['LuminateID',"Campaign_Name"])

# Following line does count of all clicks for each user  and each of his campaigns 
# and saves it in new column = 'temp'
x = df_click.assign(temp=df_click
                    .groupby(['LuminateID',"Campaign_Name"])["Clickthrough__Date"] 
                    .transform("count"))

# x.sort_values(by=['LuminateID',"Campaign_Name", 'Clickthrough__Date']).drop_duplicates(subset=['LuminateID',"Campaign_Name"])
df_click_new = x.sort_values(by=['LuminateID',"Campaign_Name", 'Clickthrough__Date']).drop_duplicates(subset=['LuminateID',"Campaign_Name"])

## One user records, this user used to have 80 clickthroughs before groupby

## Now he has 3 (one for each different campaigns)

In [891]:
df_click_new[df_click_new["LuminateID"] == 1220994]

LuminateID home_zip  Email                  Campaign_Name  \
11536     1220994  M1G 2W3  Given                     2018 T18H5   
11566     1220994  M1G 2W3  Given  General Holiday eAppeals 2017   
11504     1220994  M1G 2W3  Given                        InTouch   

                                            Message_Name Clickthrough__Date  \
11536                               T18H5 Pre Non Donors   08/30/2018 10:29   
11566  General Audience Email 2 (Subject Test Just Ha...   12/19/2017 18:36   
11504              March 2018 (Subject Line eNewsletter)   03/29/2018 10:42   

                                                  URL home_country home_phone  \
11536          https://instagram.com/trillium_health/       Canada      Given   
11566                          http://www.convio.com/       Canada      Given   
11504  https://trilliumgiving.ca/get-involved/events/       Canada      Given   

       temp  
11536    11  
11566    25  
11504    48

In [897]:
df_click[df_click["LuminateID"] == 1220994].shape

(84, 9)

# Looking at how did the dataframe size change (in bytes) from the initial csv file (percentage)

In [878]:
final_mem = df_click_new.memory_usage(index=True, deep=True).sum()
p = (start_mem /100) 
str((start_mem - final_mem) /p) + " %"

'45.340333908253 %'

# Rename columns to 

In [883]:
#(columns={'oldName1': 'newName1', 'oldName2': 'newName2'})
df_click_new = df_click_new.rename(columns={'LuminateID': 'luminateId', 'home_zip': 'zipCode',
                             "Email":"email", "Campaign_Name":"campaignName",
                             "Message_Name":"messageName","Clickthrough__Date":"date",
                             "URL":"url","home_country":"homeCountry","home_phone":"homePhone",
                             "temp":"numClicksPerCampaign"})
df_click_new.head(10)

luminateId  zipCode  email                   campaignName  \
10462     1001541  L5B 1B8  Given              2018 Spring Match   
10463     1001541  L5B 1B8  Given              Golf Classic 2018   
8009      1001702  L5E 3E1  Given              Golf Classic 2018   
1944      1001708  L5L 5S4  Given  General Holiday eAppeals 2017   
1943      1001708  L5L 5S4  Given        H6 DM campaign E-appeal   
1942      1001708  L5L 5S4  Given        H7 DM campaign E-appeal   
1945      1001708  L5L 5S4  Given                        InTouch   
500       1001711  L5L 5S4  Given                        InTouch   
9243      1001719  L5G 4N9  Given                        InTouch   
9245      1001719  L5G 4N9  Given            Laugh Out Loud 2018   

                                 messageName  clickthroughDate  \
10462                 General 2 (One Button)   06/27/2018 8:37   
10463       Golf Classic - Registration Open  03/06/2018 13:53   
8009             Joint WWD & GC Registration  04/26/2018 22:09   
1944                   Happy Holidays e-card   12/21/2017 9:46   
1943               Post-DM (Give Now Button)  11/07/2017 10:02   
1942                                  H7 Pre  11/30/2017 10:10   
1945                                  Jul-18  07/26/2018 10:03   
500                                   Jul-18  07/26/2018 13:50   
9243   March 2018 (Subject Line eNewsletter)   03/29/2018 8:56   
9245         LOL 2018 Headliner Announcement  10/20/2017 11:48   

                                                     url homeCountry  \
10462  http://thcf.convio.net/site/Donation2?df_id=27...      Canada   
10463  http://thcf.convio.net/site/Ticketing?view=Tic...      Canada   
8009                           http://www.trilliumwwd.ca      Canada   
1944   https://www.facebook.com/TrilliumHealthPartner...      Canada   
1943   http://thcf.convio.net/site/Donation2?df_id=25...      Canada   
1942              https://trilliumgiving.ca/johns-story/      Canada   
1945   https://trilliumgiving.ca/e-newsletters/indira...      Canada   
500    https://trilliumgiving.ca/e-newsletters/what-i...      Canada   
9243   https://trilliumgiving.ca/e-newsletters/what-i...      Canada   
9245   http://thcf.convio.net/site/Ticketing?view=Tic...      Canada   

      homePhone  numClicksPerCampaign  
10462     Given                     1  
10463     Given                     1  
8009      Given                     2  
1944      Given                     1  
1943      Given                     1  
1942      Given                     1  
1945      Given                     1  
500       Given                     1  
9243      Given                     2  
9245      Given                     1

# Save to new csv file

In [893]:
df_click_new.shape

(7332, 9)

In [881]:
df_click_new.to_csv("Datathon_LO_Clickthrough_CLEANED2.csv")